FORMAT: 1A

# RentHouse

Documentación de los servicios web del sistema.

# Group Auth

Grupo relacionado con la utenticación e identificación de usuarios en el sistema.

## Recurso no encontrado [/*]

Servicio que se lanza en todo momento que se quiere acceder a un recurso que no existe.

### Not Found [GET]

+ Response 404 (application/json)

        {
            "status": "Not Found",
            "data": []
        }

## Login [/login]

Servicio con el cual se identifica a un usuario frente al sistema.
Los mensajes en el Response 409 pueden variar según las condiciones de la petición.

- La primer Respuesta 200 es para un login de tipo rol propietario, inquilino o trabajador.
- La segunda Respuesta 200 es par aun login de tipo rol representante legal lo que quiere decir una inmobiliaria.

### Login [POST]

+ Request (application/json)

    + Body

            {
                "email": "cristian@gyffu.com",
                "password" : "password1234",
                "role": 0,
                "type": "1"
            }

    + Schema
            
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "required" : [
                "email",
                "password",
                "role"
              ],
              "properties": {
                "email": {
                  "type": "string",
                  "description": "Correo del usuario"
                },
                "password": {
                  "type": "string",
                  "description": "Contraseña del usuario"
                },
                "role": {
                    "type": "integer/string",
                    "description": "tipo del rol con el que se desea auntenticar",
                    "values": [
                        0: "Inidica rol propietario",
                        1: "Inidica rol inquilino",
                        2: "Inidica rol trabajador",
                        3: "Inidica rol de representante legal de una inmobiliaria"
                    ]
                },
                "type": {
                  "type": "integer/string",
                  "values": [
                    0: "Login desde sitios web",
                    1: "Login desde sitios App móvil"
                  ],
                  "description": "Tipo de login 0 para login desde web, 1 para login desde móvil, valor por defecto 0"
                },
              }
            }                        

+ Response 200 (application/json)

        {
            "status": "Login",
            "data": {
                "user": {
                    "id": "1",
                    "email": "cristian@gyffu.com",
                    "identifier": "1096038301",
                    "name": "Cristian",
                    "last_name": "Zapata",
                    "phone": "3217837066",
                    "date_birth": "1995-06-30",
                    "role": "1"
                },
                "token": "VK77ADl2P9RM9uW/it5BTgqkuHhS+ot1hU6Jsix19lyvGadrrQjcKgbC1KGHJWs6MVhrQb4QUWsv0g=="
            }
        }

+ Response 200 (application/json)

        {
            "status": "Login",
            "data": {
                "real_estate": {
                    "id": "1",
                    "nit": "10987458-1",
                    "business_name": "Empresa Pruebas",
                    "legal_representative": {
                        "id": "2",
                        "email": "empresa@empresa.com",
                        "identifier": "14785471025",
                        "name": "Juan",
                        "last_name": "Perez",
                        "phone": "3214587410",
                        "date_birth": "1990-06-30 00:00:00",
                        "role": "3"
                    }
                },
                "token": "NwxReiD4ZVvdGgK6C5SZwDECN/oAz5Rf4bN4/HNIKvRPRittDY7GQFCdt9LSgadv1HRt06aQoznWvxVGXqPt"
            }
        }

+ Response 409 (application/json)

        {
            "status": "Not login",
            "messages": [
                {
                    "message": "Correo/Contraseña/Rol incorrectos",
                    "field": "login",
                    "type": "identifier"
                },
                {
                    "message": "El campo email es obligatorio",
                    "field": "email",
                    "type": "missing"
                },
                {
                    "message": "El campo password es obligatorio",
                    "field": "password",
                    "type": "missing"
                },
                {
                    "message": "El campo role es obligatorio",
                    "field": "role",
                    "type": "missing"
                }
            ]
        }

## Registro Usuario [/register]

Servicio para realizar el registro de un usuario en el sistema quien puede ser una persona natural o inmobiliaria.
Los mensajes en el Response 409 pueden variar según las condiciones de la petición.

- El primer Request y Response corresponde a un registro de un usuario natural. Es decir Rol 0 y 1.
- El segundo Request y Response correspondea a u registro de una inmobiliaria. Es decir Rol 3.

### Registro Usuario [POST]

+ Request (application/json)

    + Body

            {
                "name": "Camilo",
                "last_name" : "Aguiire",
                "identifier": "789",
                "phone": "57484",
                "date_birth": "2010-02-20",
                "email": "aguirre@correo.com",
                "password": "12314567890",
                "confirm": "12314567890",
                "role": "1"
            }

    + Schema
            
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "required" : [
                "name",
                "lastName",
                "identifier",
                "phone",
                "dateBirth",
                "email",
                "password",
                "confirm",
                "role"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Nombre del usuario"
                },
                "last_name": {
                  "type": "string",
                  "description": "Apellidos del usuario"
                },
                "identifier": {
                  "type": "string",
                  "description": "identificación del usuario"
                },
                "phone": {
                  "type": "string",
                  "description": "Celular del usuario"
                },
                "date_birth": {
                  "type": "string",
                  "description": "Fecha de nacimiento del usuario",
                  "format": "YYYY-MM-DD"
                },
                "email": {
                  "type": "string",
                  "description": "Correo del usuario"
                },
                "password": {
                  "type": "string",
                  "description": "Contraseña del usuario",
                  "minLength": 10
                },
                "confirm": {
                  "type": "string",
                  "description": "confirmación y/o retepitición de la contraseña"
                },
                "role": {
                  "type": "integer/string",
                  "description": "tipo de rol del usuario",
                  "values": [
                    0: "propietario",
                    1: "inquilino"
                  ]
                }
              }
            }

+ Response 200 (application/json)

        {
            "status": "Ok",
            "data": {
                "user": {
                    "id": "8",
                    "email": "aguirre@correo.com",
                    "identifier": "789",
                    "name": "Camilo",
                    "last_name": "Aguiire",
                    "phone": "57484",
                    "date_birth": "2010-02-20",
                    "role": "1"
                }
            }
        }

+ Request (application/json)

    + Body

            {
                "name": "Carolina",
                "last_name" : "Tabares",
                "identifier": "12222",
                "phone": "3334555",
                "date_birth": "2010-02-20",
                "email": "correo@correo.com",
                "password": "12314567890",
                "confirm": "12314567890",
                "role": "3",
                "nit" : "1478521-1",
                "business_name": "My company"
            }

    + Schema
            
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "required" : [
                "name",
                "lastName",
                "identifier",
                "phone",
                "dateBirth",
                "email",
                "password",
                "confirm",
                "role"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Nombre del usuario"
                },
                "last_name": {
                  "type": "string",
                  "description": "Apellidos del usuario"
                },
                "identifier": {
                  "type": "string",
                  "description": "identificación del usuario"
                },
                "phone": {
                  "type": "string",
                  "description": "Celular del usuario"
                },
                "date_birth": {
                  "type": "string",
                  "description": "Fecha de nacimiento del usuario",
                  "format": "YYYY-MM-DD"
                },
                "email": {
                  "type": "string",
                  "description": "Correo del usuario"
                },
                "password": {
                  "type": "string",
                  "description": "Contraseña del usuario",
                  "minLength": 10
                },
                "confirm": {
                  "type": "string",
                  "description": "confirmación y/o retepitición de la contraseña"
                },
                "role": {
                  "type": "integer/string",
                  "description": "tipo de rol del usuario",
                  "values": [
                    0: "propietario",
                    1: "inquilino"
                  ]
                },
                "nit": {
                  "type": "string",
                  "description": "identificación de la empresa"
                },
                "business_name": {
                  "type": "string",
                  "description": "razón social de la empresa"
                },
              }
            }

+ Response 200 (application/json)

        {
            "status": "Ok",
            "data": {
                "real_estate": {
                    "id": "3",
                    "nit": "14782521-1",
                    "business_name": "My company",
                    "legal_representative": {
                        "id": "10",
                        "email": "correo@correo.com",
                        "identifier": "12222",
                        "name": "Carolina",
                        "last_name": "Tabares",
                        "phone": "3334555",
                        "date_birth": "2010-02-20",
                        "role": "3"
                    }
                }
            }
        }

+ Response 409 (application/json)

        {
            "status": "Not register",
            "messages": [
                {
                    "message": "El correo ingresado ya está en uso",
                    "field": "email",
                    "type": "Uniqueness"
                },
                {
                    "message": "El número de télefono ingresado ya está en uso",
                    "field": "phone",
                    "type": "Uniqueness"
                },
                {
                    "message": "El número de identificación ingresado ya está en uso",
                    "field": "identifier",
                    "type": "Uniqueness"
                },
                {
                    "message": "El contraseña y su confirmación no coinciden",
                    "field": "password",
                    "type": "unequal"
                },
                {
                    "message": "El formato de la fecha de nacimiento es inválida. (YYY-MM-DD)",
                    "field": "dateBirth",
                    "type": "format"
                },
                {
                    "message": "El campo name es obligatorio",
                    "field": "name",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo lastName es obligatorio",
                    "field": "lastName",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo identifier es obligatorio",
                    "field": "identifier",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo phone es obligatorio",
                    "field": "phone",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo dateBirth es obligatorio",
                    "field": "dateBirth",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo email es obligatorio",
                    "field": "email",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo password es obligatorio",
                    "field": "password",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo confirm es obligatorio",
                    "field": "confirm",
                    "type": "PresenceOf"
                },
                {
                    "message": "El campo role es obligatorio",
                    "field": "role",
                    "type": "PresenceOf"
                },
                {
                    "message": "El nit ingresado ya está en uso",
                    "field": "nit",
                    "type": "Uniqueness"
                }
            ]
        }

# Group Property

Grupo relacionado con la gestiona de las propiedades del sistema, los usuarios que pueden gestionar
las propiedades crear, editar, eliminar son aquellos que estan identificados como propietario y/o representante legal.

## Obtener Propiedad [/property/{id}]

Servicio para obtener una propiedad del sistema siempre y cuando esta esté relacionada con el usuario de rol propietario o inmobiliaria (representante legal).

- En caso de querer consumir el servicio con un usuario de rol diferente a los mencionados el recurso no estará disponible y retorna el servicio
'Not Found'

### Obtener Propiedad [GET]

+ Parameters
    + id (number) - Identificador de la propiedad.

+ Request

    + Headers

            Authorization: token obtenido del recurso 'Login'

+ Response 200 (application/json)

        {
            "status": "Ok",
            "data": {
                "property": {
                    "id": "1",
                    "type": "2",
                    "location": "A l45445454a vuelta de la esquina.",
                    "latitude": null,
                    "longitute": null,
                    "extention": "0",
                    "rooms": "2",
                    "bathrooms": "2",
                    "kitchen": "1",
                    "garage": "0",
                    "description": "asadadadad",
                    "cost_month": "0",
                    "deposit": "0",
                    "status": "3",
                    "user_id": "1",
                    "real_estate_id": "1",
                    "city_id": "1"
                }
            }
        }

+ Response 404 (application/json)

        {
            "status": "Not found property",
            "data": []
        }

## Listar Propiedades [/property/list/{status}]

Serivicio para obtener las propiedades todas la propiedades relacionadas con un usario de rol propietario o inmobiliaria (representante legal).

- En caso de querer consumir el servicio con un usuario de rol diferente a los mencionados el recurso no estará disponible y retorna el servicio
'Not Found'

### Listar Propiedades [GET]

+ Parameters
    + status (enum[string]) - Este sirve como filtro a la hora de listar para obtener las propiedades en un estato en concreto
        + status
            + all: No tiene encuente el estado
            + 0: Disponible
            + 1: No Disponible
            + 2: Ocupada
            + 3: Eliminada

+ Request

    + Headers

            Authorization: token obtenido del recurso 'Login'

+ Response 200 (application/json)

        {
            "status": "Ok",
            "data": {
                "first": 1,
                "before": 1,
                "current": 1,
                "last": 1,
                "next": 1,
                "total_pages": 1,
                "total_items": 1,
                "limit": 20,
                "properties": [
                    {
                        "id": "1",
                        "type": "2",
                        "location": "A l45445454a vuelta de la esquina.",
                        "latitude": null,
                        "longitute": null,
                        "extention": "0",
                        "rooms": "2",
                        "bathrooms": "2",
                        "kitchen": "1",
                        "garage": "0",
                        "description": "asadadadad",
                        "cost_month": "0",
                        "deposit": "0",
                        "status": "3",
                        "user_id": "1",
                        "real_estate_id": "1",
                        "city_id": "1"
                    }
                ]
            }
        }

+ Response 404 (application/json)

        {
            "status": "Not Found",
            "data": []
        }